# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for hex
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      patch-updates:
        update-types: ["patch"]

  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/assets"
    schedule:
      interval: "weekly"
    groups:
      minor-updates:
        update-types: ["patch", "minor"]

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
